FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Kafka Consumer script
COPY consumer.py .

CMD ["python", "consumer.py"]
