apiVersion: 1

datasources:
  - name: QuestDB
    type: postgres
    access: proxy
    url: ${QUESTDB_HOST}:${QUESTDB_PORT}
    database: ${QUESTDB_DB}
    user: ${QUESTDB_USER}
    password: ${QUESTDB_PASSWORD}
    jsonData:
      tlsSkipVerify: true
      queryTimeout: 60
      sslmode: 'disable'
    secureJsonData:
      password: ${QUESTDB_PASSWORD}