{
 "title": "Stock analytics",
 "time": { "from": "2025-01-24T15:54:03.001Z", "to": "2025-01-24T17:43:10.857Z" },
 "refresh": "1m",
 "panels": [
  {
   "title": "RSI 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT RSI_10 ,local_time as time FROM stock_data where stock_symbol = 'BTCIRT'"
    }
   ]
  },
  {
   "title": "SMA 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SMA_5, local_time as time FROM stock_data where stock_symbol = 'BTCIRT'"
    }
   ]
  },
  {
   "title": "EMA 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT EMA_10 ,local_time as time FROM stock_data where stock_symbol = 'BTCIRT'"
    }
   ]
  },
  {
   "title": "Gain and Loss",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT gain, loss, local_time as time from stock_data WHERE stock_symbol= 'BTCIRT'"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT signal, local_time\r\nFROM stock_data\r\nWHERE stock_symbol = 'BTCIRT'\r\nORDER BY local_time DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Close price",
   "type": "stat",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Max(close), avg(close), Min(close) FROM stock_data where stock_symbol='BTCIRT'"
    }
   ]
  },
  {
   "title": "Candlestick",
   "type": "candlestick",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    local_time AS \"time\", open, close, high, low, volume, SMA_5, EMA_10\r\nFROM\r\n    stock_data\r\nWHERE\r\n    $__timeFilter(local_time) AND\r\n    stock_symbol = 'BTCIRT' AND SMA_5 > 0 AND EMA_10 > 0\r\nORDER BY\r\n    local_time;"
    }
   ]
  },
  {
   "title": "Stock's Average gains",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    AVG(CASE WHEN stock_symbol = 'SHIBIRT' THEN gain END) AS avg_gain_shibirt,\r\n    AVG(CASE WHEN stock_symbol = 'ETCIRT' THEN gain END) AS avg_gain_etcirt,\r\n    AVG(CASE WHEN stock_symbol = 'BTCIRT' THEN gain END) AS avg_gain_btcirt,\r\n    AVG(CASE WHEN stock_symbol = 'USDTIRT' THEN gain END) AS avg_gain_usdtirt\r\n\r\nFROM stock_data\r\nWHERE stock_symbol IN ('ETCIRT', 'SHIBIRT','BTCIRT','USDTIRT');"
    }
   ]
  },
  {
   "title": "Stock's average losses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    AVG(CASE WHEN stock_symbol = 'SHIBIRT' THEN loss END) AS avg_loss_shibirt,\r\n    AVG(CASE WHEN stock_symbol = 'ETCIRT' THEN loss END) AS avg_loss_etcirt,\r\n    AVG(CASE WHEN stock_symbol = 'BTCIRT' THEN loss END) AS avg_loss_btcirt,\r\n    AVG(CASE WHEN stock_symbol = 'USDTIRT' THEN loss END) AS avg_loss_usdtirt\r\n\r\nFROM stock_data\r\nWHERE stock_symbol IN ('ETCIRT', 'SHIBIRT','BTCIRT','USDTIRT');"
    }
   ]
  }
 ]
}