{
 "title": "Stock analytics",
 "time": { "from": "2025-01-24T15:54:03.001Z", "to": "2025-01-24T17:43:10.857Z" },
 "refresh": "1m",
 "panels": [
  {
   "title": "RSI 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT RSI_10 ,local_time as time FROM stock_data where stock_symbol = 'BTCIRT'"
    }
   ]
  },
  {
   "title": "SMA 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SMA_5, local_time as time FROM stock_data where stock_symbol = 'BTCIRT'"
    }
   ]
  },
  {
   "title": "EMA 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT EMA_10 ,local_time as time FROM stock_data where stock_symbol = 'BTCIRT'"
    }
   ]
  },
  {
   "title": "Gain and Loss",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT gain, loss, local_time as time from stock_data WHERE stock_symbol= 'BTCIRT'"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT signal, local_time\r\nFROM stock_data\r\nWHERE stock_symbol = 'BTCIRT'\r\nORDER BY local_time DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Candlestick",
   "type": "candlestick",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    local_time AS \"time\", open, close, high, low, volume, SMA_5, EMA_10\r\nFROM\r\n    stock_data\r\nWHERE\r\n    $__timeFilter(local_time) AND\r\n    stock_symbol = 'BTCIRT' AND SMA_5 > 0 AND EMA_10 > 0\r\nORDER BY\r\n    local_time;"
    }
   ]
  }
 ]
}