
apiVersion: v1
kind: Service
metadata:
  name: questdb-service
spec:
  type: NodePort
  selector:
    app: questdb
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30090
  - name: tcp
    protocol: TCP
    port: 8812
    targetPort: 8812
    nodePort: 30091
