apiVersion: v1
kind: Pod
metadata:
  name: spark-pod
spec:
  containers:
    - name: spark-container
      image: bitnami/spark:latest
      ports:
        - containerPort: 7077  
        - containerPort: 8080
      env:
        - name: SPARK_MODE
          value: "master"
      resources:
        limits:
          memory: "2Gi"
          cpu: "2"
